import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Akif Kadıoğlu',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='container mx-auto font-mono px-3 dark:bg-zinc-900 dark:text-zinc-100'>
        {children}
      </body>
    </html>
  )
}
